/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Models(props) {
  const { nodes, materials } = useGLTF('/models/CityPack.gltf')
  return (
    <group {...props} dispose={null}>
      <group name="City" position={[-426.6393, -110.78746, -532.77203]}>
        <group name="Cars" position={[57.57023, 20.08391, -387.38716]}>
          <mesh
            name="CAR_03_1"
            castShadow
            receiveShadow
            geometry={nodes.CAR_03_1.geometry}
            material={materials['World ap']}
            position={[22.13131, 15.53384, -475.07097]}
            rotation={[-Math.PI, 0.73166, Math.PI]}
            scale={1.5}
          />
          <mesh
            name="CAR_03"
            castShadow
            receiveShadow
            geometry={nodes.CAR_03.geometry}
            material={materials['World ap']}
            position={[-281.15509, 14.66318, 108.45244]}
            rotation={[Math.PI, 1.54445, -Math.PI]}
            scale={1.5}
          />
          <mesh
            name="Car_04"
            castShadow
            receiveShadow
            geometry={nodes.Car_04.geometry}
            material={materials['World ap']}
            position={[-302.7033, 21.4496, 233.83568]}
            rotation={[0, 1.57025, 0]}
            scale={1.5}
          />
          <mesh
            name="CAR_03_2"
            castShadow
            receiveShadow
            geometry={nodes.CAR_03_2.geometry}
            material={materials['World ap']}
            position={[-478.5302, 14.66318, 1463.23597]}
            rotation={[Math.PI, -1.457, Math.PI]}
            scale={1.5}
          />
          <mesh
            name="Car_04_1"
            castShadow
            receiveShadow
            geometry={nodes.Car_04_1.geometry}
            material={materials['World ap']}
            position={[-445.67431, 21.4496, -438.26853]}
            rotation={[0, 1.57025, 0]}
            scale={1.5}
          />
          <mesh
            name="Car_04_2"
            castShadow
            receiveShadow
            geometry={nodes.Car_04_2.geometry}
            material={materials['World ap']}
            position={[-1097.65418, 23.05317, 1026.10284]}
            rotation={[Math.PI, -0.00662, Math.PI]}
            scale={1.5}
          />
          <mesh
            name="Car_04_3"
            castShadow
            receiveShadow
            geometry={nodes.Car_04_3.geometry}
            material={materials['World ap']}
            position={[449.95365, 21.4496, 544.78297]}
            rotation={[Math.PI, -1.57025, Math.PI]}
            scale={1.5}
          />
          <mesh
            name="Car_04_4"
            castShadow
            receiveShadow
            geometry={nodes.Car_04_4.geometry}
            material={materials['World ap']}
            position={[780.42403, 21.4496, -35.69159]}
            rotation={[Math.PI, 0.00055, -Math.PI]}
            scale={1.5}
          />
          <mesh
            name="Car_08_4"
            castShadow
            receiveShadow
            geometry={nodes.Car_08_4.geometry}
            material={materials['World ap.8']}
            position={[938.82004, -18.35059, 754.08582]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={1.5}
          />
          <mesh
            name="Car_08_3"
            castShadow
            receiveShadow
            geometry={nodes.Car_08_3.geometry}
            material={materials['World ap.9']}
            position={[187.86569, -20.44754, 1351.53859]}
            rotation={[Math.PI / 2, 0, 3.10475]}
            scale={1.5}
          />
          <mesh
            name="Car_04_1_2"
            castShadow
            receiveShadow
            geometry={nodes.Car_04_1_2.geometry}
            material={materials['World ap']}
            position={[-719.8219, 21.4496, 374.47565]}
            rotation={[0, 1.54625, 0]}
            scale={1.5}
          />
          <mesh
            name="Car_08_2"
            castShadow
            receiveShadow
            geometry={nodes.Car_08_2.geometry}
            material={materials['World ap.11']}
            position={[-271.22229, -14.73233, -95.64426]}
            rotation={[Math.PI / 2, 0, -0.21519]}
            scale={1.5}
          />
          <mesh
            name="CAR_03_1_2"
            castShadow
            receiveShadow
            geometry={nodes.CAR_03_1_2.geometry}
            material={materials['World ap']}
            position={[81.42254, 14.66317, 401.82695]}
            rotation={[-Math.PI, 1.5576, Math.PI]}
            scale={1.5}
          />
          <mesh
            name="CAR_03_2_2"
            castShadow
            receiveShadow
            geometry={nodes.CAR_03_2_2.geometry}
            material={materials['World ap']}
            position={[-661.16805, 15.54939, 533.57484]}
            rotation={[0, -1.50317, 0]}
            scale={1.5}
          />
          <mesh
            name="Car_04_2_2"
            castShadow
            receiveShadow
            geometry={nodes.Car_04_2_2.geometry}
            material={materials['World ap']}
            position={[574.36538, 21.4496, -216.99189]}
            rotation={[Math.PI, 1.35522, -Math.PI]}
            scale={1.5}
          />
          <mesh
            name="Car_08_1"
            castShadow
            receiveShadow
            geometry={nodes.Car_08_1.geometry}
            material={materials['World ap.15']}
            position={[-581.17235, -14.73233, -559.03441]}
            rotation={[Math.PI / 2, 0, -Math.PI]}
            scale={1.5}
          />
          <mesh
            name="Car_08"
            castShadow
            receiveShadow
            geometry={nodes.Car_08.geometry}
            material={materials['World ap.16']}
            position={[-6.17049, -19.0395, 785.6159]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={1.5}
          />
          <mesh
            name="Car_08_5"
            castShadow
            receiveShadow
            geometry={nodes.Car_08_5.geometry}
            material={materials['World ap.17']}
            position={[565.84948, -18.27294, -425.91353]}
            rotation={[Math.PI / 2, 0, -0.03684]}
            scale={1.5}
          />
          <mesh
            name="CAR_03_2_3"
            castShadow
            receiveShadow
            geometry={nodes.CAR_03_2_3.geometry}
            material={materials['World ap']}
            position={[-932.31731, 14.66317, -406.06474]}
            rotation={[0, -1.11395, 0]}
            scale={1.5}
          />
          <mesh
            name="Car_08_6"
            castShadow
            receiveShadow
            geometry={nodes.Car_08_6.geometry}
            material={materials['World ap.19']}
            position={[-6.17049, -20.56176, 1020.42283]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={1.5}
          />
          <mesh
            name="CAR_03_3"
            castShadow
            receiveShadow
            geometry={nodes.CAR_03_3.geometry}
            material={materials['World ap']}
            position={[940.96566, 15.30536, -243.44926]}
            rotation={[0, 0.09833, 0]}
            scale={1.5}
          />
        </group>
        <group
          name="Block_2"
          position={[-431.43073, 57.00889, 557.2859]}
          rotation={[0, Math.PI / 2, 0]}>
          <group name="Lights" position={[-152.77237, -44.68044, -137.83876]}>
            <mesh
              name="traffic_light"
              castShadow
              receiveShadow
              geometry={nodes.traffic_light.geometry}
              material={materials['World ap']}
              position={[474.59854, 66.93382, -256.17817]}
              rotation={[0, -Math.PI / 2, 0]}
            />
            <mesh
              name="Light_3"
              castShadow
              receiveShadow
              geometry={nodes.Light_3.geometry}
              material={materials['World ap']}
              position={[403.84156, -14.34028, 382.06205]}
              rotation={[0, Math.PI / 2, 0]}
            />
            <mesh
              name="Light_2"
              castShadow
              receiveShadow
              geometry={nodes.Light_2.geometry}
              material={materials['World ap']}
              position={[-82.27713, -14.34029, 382.0621]}
              rotation={[0, Math.PI / 2, 0]}
            />
            <mesh
              name="Light_1"
              castShadow
              receiveShadow
              geometry={nodes.Light_1.geometry}
              material={materials['World ap']}
              position={[403.84149, -14.3403, -257.03959]}
              rotation={[0, -Math.PI / 2, 0]}
            />
            <mesh
              name="Light"
              castShadow
              receiveShadow
              geometry={nodes.Light.geometry}
              material={materials['World ap']}
              position={[-82.27719, -14.34027, -257.03953]}
              rotation={[0, -Math.PI / 2, 0]}
            />
            <mesh
              name="traffic_light_1"
              castShadow
              receiveShadow
              geometry={nodes.traffic_light_1.geometry}
              material={materials['World ap']}
              position={[-160.49175, 66.93382, -256.17805]}
              rotation={[0, -Math.PI / 2, 0]}
            />
            <mesh
              name="traffic_light_2"
              castShadow
              receiveShadow
              geometry={nodes.traffic_light_2.geometry}
              material={materials['World ap']}
              position={[474.59866, 66.93384, 379.60708]}
              rotation={[0, -Math.PI / 2, 0]}
            />
          </group>
          <group name="Base_1" position={[1.90139, -22.36203, -74.2372]}>
            <mesh
              name="Floor_4"
              castShadow
              receiveShadow
              geometry={nodes.Floor_4.geometry}
              material={materials['World ap']}
              position={[0, -2.84271, 0]}
            />
            <mesh
              name="Floor"
              castShadow
              receiveShadow
              geometry={nodes.Floor.geometry}
              material={materials['World ap']}
              position={[0, 2.84271, 0]}
            />
          </group>
          <group name="Bushes" position={[-194.20206, -41.06844, -31.50551]}>
            <mesh
              name="Bed"
              castShadow
              receiveShadow
              geometry={nodes.Bed.geometry}
              material={materials['World ap']}
              position={[3.1416, -17.39266, -42.03307]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              name="Bushes_3"
              castShadow
              receiveShadow
              geometry={nodes.Bushes_3.geometry}
              material={materials['World ap']}
              position={[-1.04722, 5.79755, -183.50409]}
              rotation={[-1.38248, -1.39866, -0.0417]}
            />
          </group>
          <group name="Bushes_1" position={[263.14361, -41.06844, -31.50554]}>
            <mesh
              name="Bed_2"
              castShadow
              receiveShadow
              geometry={nodes.Bed_2.geometry}
              material={materials['World ap']}
              position={[3.1416, -17.39266, -42.03307]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              name="Bushes_3_2"
              castShadow
              receiveShadow
              geometry={nodes.Bushes_3_2.geometry}
              material={materials['World ap']}
              position={[-1.04722, 5.79755, -183.50409]}
              rotation={[-1.38248, -1.39866, -0.0417]}
            />
          </group>
          <mesh
            name="House"
            castShadow
            receiveShadow
            geometry={nodes.House.geometry}
            material={materials['World ap']}
            position={[0.00039, 104.49888, 143.57932]}
            rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              name="Antenne"
              castShadow
              receiveShadow
              geometry={nodes.Antenne.geometry}
              material={materials['World ap']}
              position={[30.45886, -360.42025, -350.95336]}
              rotation={[2.58233, 1.08638, -0.95518]}
            />
            <mesh
              name="Antenne_1"
              castShadow
              receiveShadow
              geometry={nodes.Antenne_1.geometry}
              material={materials['World ap']}
              position={[21.12193, -290.59952, -321.60666]}
              rotation={[-2.22096, 0.86041, -2.61862]}
            />
          </mesh>
        </group>
        <group name="Block_4" position={[511.36257, 22.14579, 541.22529]}>
          <group name="Lights_2" position={[-201.53298, -9.81735, -54.04065]}>
            <mesh
              name="Light_3_2"
              castShadow
              receiveShadow
              geometry={nodes.Light_3_2.geometry}
              material={materials['World ap']}
              position={[342.30674, -14.34026, 382.06209]}
              rotation={[0, Math.PI / 2, 0]}
            />
            <mesh
              name="Light_2_2"
              castShadow
              receiveShadow
              geometry={nodes.Light_2_2.geometry}
              material={materials['World ap']}
              position={[-82.27716, -14.34029, 382.06209]}
              rotation={[0, Math.PI / 2, 0]}
            />
            <mesh
              name="Light_1_2"
              castShadow
              receiveShadow
              geometry={nodes.Light_1_2.geometry}
              material={materials['World ap']}
              position={[342.30674, -14.34028, -262.32624]}
              rotation={[0, -Math.PI / 2, 0]}
            />
            <mesh
              name="Light_2_3"
              castShadow
              receiveShadow
              geometry={nodes.Light_2_3.geometry}
              material={materials['World ap']}
              position={[-82.27716, -14.34028, -262.32624]}
              rotation={[0, -Math.PI / 2, 0]}
            />
          </group>
          <group name="Base" position={[-66.16219, 12.50107, 7.29611]}>
            <mesh
              name="Floor_4_2"
              castShadow
              receiveShadow
              geometry={nodes.Floor_4_2.geometry}
              material={materials['World ap']}
              position={[0, -0.85749, 0]}
            />
            <mesh
              name="Floor_2"
              castShadow
              receiveShadow
              geometry={nodes.Floor_2.geometry}
              material={materials['World ap']}
              position={[0, 4.82792, 0]}
            />
          </group>
          <group
            name="Trees"
            position={[-73.04728, -36.01238, -229.5517]}
            rotation={[0, -Math.PI / 2, 0]}>
            <mesh
              name="Firtree_47"
              castShadow
              receiveShadow
              geometry={nodes.Firtree_47.geometry}
              material={materials['World ap']}
              position={[-9.32251, -17.95502, 195.55067]}
            />
            <mesh
              name="Firtree_3"
              castShadow
              receiveShadow
              geometry={nodes.Firtree_3.geometry}
              material={materials['World ap']}
              position={[8.9936, 9.32948, 112.13508]}
            />
            <mesh
              name="Firtree_2"
              castShadow
              receiveShadow
              geometry={nodes.Firtree_2.geometry}
              material={materials['World ap']}
              position={[4.29529, 1.08363, 31.6032]}
            />
            <mesh
              name="Firtree_1"
              castShadow
              receiveShadow
              geometry={nodes.Firtree_1.geometry}
              material={materials['World ap']}
              position={[-9.61407, -11.24544, -45.04547]}
            />
            <mesh
              name="Firtree"
              castShadow
              receiveShadow
              geometry={nodes.Firtree.geometry}
              material={materials['World ap']}
              position={[-3.04589, -11.95998, -133.05637]}
            />
            <mesh
              name="Cube_7"
              castShadow
              receiveShadow
              geometry={nodes.Cube_7.geometry}
              material={materials['World ap']}
              position={[-19.8409, 13.99556, -8.47645]}
            />
            <mesh
              name="Firtree_4"
              castShadow
              receiveShadow
              geometry={nodes.Firtree_4.geometry}
              material={materials['World ap']}
              position={[8.20825, -0.7818, -227.08114]}
              rotation={[0, 0.81518, 0]}
            />
          </group>
          <mesh
            name="Antenne_2"
            castShadow
            receiveShadow
            geometry={nodes.Antenne_2.geometry}
            material={materials['World ap']}
            position={[-201.32658, 469.80603, 126.57183]}
            rotation={[-2.19842, -0.24967, 0.10977]}
          />
          <mesh
            name="Bench_1"
            castShadow
            receiveShadow
            geometry={nodes.Bench_1.geometry}
            material={materials['World ap']}
            position={[138.12872, -19.65213, 19.71995]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          />
          <mesh
            name="House_2"
            castShadow
            receiveShadow
            geometry={nodes.House_2.geometry}
            material={materials['World ap']}
            position={[131.58217, -47.96152, 121.88464]}
            rotation={[0, -Math.PI / 2, 0]}
          />
          <mesh
            name="Bench"
            castShadow
            receiveShadow
            geometry={nodes.Bench.geometry}
            material={materials['World ap']}
            position={[138.12872, -19.65213, -109.69648]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          />
          <mesh
            name="Antenne_1_2"
            castShadow
            receiveShadow
            geometry={nodes.Antenne_1_2.geometry}
            material={materials['World ap']}
            position={[-94.33851, 453.46968, 128.85249]}
            rotation={[-2.18664, 0.28074, -0.59167]}
          />
        </group>
        <group name="Block_1" position={[504.12562, 22.14579, -408.51273]}>
          <group name="Lights_3" position={[-201.53298, -9.81735, -54.04065]}>
            <mesh
              name="Light_3_3"
              castShadow
              receiveShadow
              geometry={nodes.Light_3_3.geometry}
              material={materials['World ap']}
              position={[342.30674, -14.34026, 382.06209]}
              rotation={[0, Math.PI / 2, 0]}
            />
            <mesh
              name="Light_2_4"
              castShadow
              receiveShadow
              geometry={nodes.Light_2_4.geometry}
              material={materials['World ap']}
              position={[-82.27716, -14.34029, 382.06209]}
              rotation={[0, Math.PI / 2, 0]}
            />
            <mesh
              name="Light_1_3"
              castShadow
              receiveShadow
              geometry={nodes.Light_1_3.geometry}
              material={materials['World ap']}
              position={[342.30674, -14.34028, -262.32624]}
              rotation={[0, -Math.PI / 2, 0]}
            />
            <mesh
              name="Light_3_4"
              castShadow
              receiveShadow
              geometry={nodes.Light_3_4.geometry}
              material={materials['World ap']}
              position={[-82.27716, -14.34028, -262.32624]}
              rotation={[0, -Math.PI / 2, 0]}
            />
            <mesh
              name="Light_4"
              castShadow
              receiveShadow
              geometry={nodes.Light_4.geometry}
              material={materials['World ap']}
              position={[456.32726, -14.34026, 37.56165]}
              rotation={[-Math.PI, 0, Math.PI]}
            />
            <mesh
              name="Light_5"
              castShadow
              receiveShadow
              geometry={nodes.Light_5.geometry}
              material={materials['World ap']}
              position={[456.32726, -14.34026, 1034.84356]}
              rotation={[-Math.PI, 0, Math.PI]}
            />
          </group>
          <group name="Base_2" position={[-66.16219, 12.50107, 7.29611]}>
            <mesh
              name="Floor_4_3"
              castShadow
              receiveShadow
              geometry={nodes.Floor_4_3.geometry}
              material={materials['World ap']}
              position={[0, -0.85749, 0]}
            />
            <mesh
              name="Floor_3"
              castShadow
              receiveShadow
              geometry={nodes.Floor_3.geometry}
              material={materials['World ap']}
              position={[0, 4.82792, 0]}
            />
          </group>
          <group name="Trees_2" position={[-305.4674, -36.01239, 2.86842]}>
            <mesh
              name="Firtree_47_2"
              castShadow
              receiveShadow
              geometry={nodes.Firtree_47_2.geometry}
              material={materials['World ap']}
              position={[-9.32249, -17.95502, 195.55067]}
            />
            <mesh
              name="Firtree_3_2"
              castShadow
              receiveShadow
              geometry={nodes.Firtree_3_2.geometry}
              material={materials['World ap']}
              position={[8.99361, 9.32949, 112.13508]}
            />
            <mesh
              name="Firtree_2_2"
              castShadow
              receiveShadow
              geometry={nodes.Firtree_2_2.geometry}
              material={materials['World ap']}
              position={[4.2953, 1.08363, 31.6032]}
            />
            <mesh
              name="Firtree_1_2"
              castShadow
              receiveShadow
              geometry={nodes.Firtree_1_2.geometry}
              material={materials['World ap']}
              position={[-9.61407, -11.24544, -45.04547]}
            />
            <mesh
              name="Firtree_2_3"
              castShadow
              receiveShadow
              geometry={nodes.Firtree_2_3.geometry}
              material={materials['World ap']}
              position={[-3.04591, -11.95998, -133.05637]}
            />
            <mesh
              name="Cube_7_2"
              castShadow
              receiveShadow
              geometry={nodes.Cube_7_2.geometry}
              material={materials['World ap']}
              position={[-18.89871, 13.99556, -1.57774]}
            />
            <mesh
              name="Firtree_4_2"
              castShadow
              receiveShadow
              geometry={nodes.Firtree_4_2.geometry}
              material={materials['World ap']}
              position={[8.20822, -0.7818, -227.08114]}
              rotation={[0, 0.81518, 0]}
            />
          </group>
          <mesh
            name="Muff_1"
            castShadow
            receiveShadow
            geometry={nodes.Muff_1.geometry}
            material={materials['World ap']}
            position={[111.52333, 20.05301, 89.04898]}
          />
          <mesh
            name="Muff"
            castShadow
            receiveShadow
            geometry={nodes.Muff.geometry}
            material={materials['World ap']}
            position={[111.52333, 20.05301, 188.91306]}
          />
          <mesh
            name="Bench_2"
            castShadow
            receiveShadow
            geometry={nodes.Bench_2.geometry}
            material={materials['World ap']}
            position={[-186.91552, -19.65213, -230.34256]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            name="Behch"
            castShadow
            receiveShadow
            geometry={nodes.Behch.geometry}
            material={materials['World ap']}
            position={[-186.91552, -19.65213, -152.0117]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            name="House_3"
            castShadow
            receiveShadow
            geometry={nodes.House_3.geometry}
            material={materials['World ap']}
            position={[-82.28498, 5.95816, -23.08022]}
          />
        </group>
        <group
          name="Block_3"
          position={[-511.82376, 22.14579, -462.47224]}
          rotation={[0, Math.PI / 2, 0]}>
          <group name="Lights_4" position={[-201.53299, -9.81734, -54.04062]}>
            <mesh
              name="Light_3_5"
              castShadow
              receiveShadow
              geometry={nodes.Light_3_5.geometry}
              material={materials['World ap']}
              position={[413.75409, -15.93365, 144.86748]}
              rotation={[0, Math.PI / 2, 0]}
            />
            <mesh
              name="Light_2_5"
              castShadow
              receiveShadow
              geometry={nodes.Light_2_5.geometry}
              material={materials['World ap']}
              position={[-134.67508, -15.93367, 145.28273]}
              rotation={[0, Math.PI / 2, 0]}
            />
            <mesh
              name="Light_4_2"
              castShadow
              receiveShadow
              geometry={nodes.Light_4_2.geometry}
              material={materials['World ap']}
              position={[154.50833, -15.93365, -264.62917]}
              rotation={[0, -Math.PI / 2, 0]}
            />
          </group>
          <group name="Base_3" position={[-66.16219, 12.50108, 7.29612]}>
            <mesh
              name="Floor_4_4"
              castShadow
              receiveShadow
              geometry={nodes.Floor_4_4.geometry}
              material={materials['World ap']}
              position={[0, 5.02996, 0]}
            />
            <mesh
              name="Floor_4_5"
              castShadow
              receiveShadow
              geometry={nodes.Floor_4_5.geometry}
              material={materials['World ap']}
              position={[70.75896, 3.39093, 277.50182]}
            />
          </group>
          <group
            name="Bushes_1_2"
            position={[-356.01426, -14.54642, -70.98412]}
            rotation={[Math.PI, 0, Math.PI]}>
            <mesh
              name="Bed_3"
              castShadow
              receiveShadow
              geometry={nodes.Bed_3.geometry}
              material={materials['World ap']}
              position={[2.856, -15.8115, -38.21188]}
              rotation={[-Math.PI, 0, Math.PI]}
            />
            <mesh
              name="Bushes_15"
              castShadow
              receiveShadow
              geometry={nodes.Bushes_15.geometry}
              material={materials['World ap']}
              position={[-0.952, 5.2705, 177.88306]}
              rotation={[-1.38248, -1.39866, -0.0417]}
            />
            <mesh
              name="Bushes_2"
              castShadow
              receiveShadow
              geometry={nodes.Bushes_2.geometry}
              material={materials['World ap']}
              position={[-0.952, 5.2705, -52.61977]}
              rotation={[-1.38248, -1.39866, -0.0417]}
            />
            <mesh
              name="Bushes_2_2"
              castShadow
              receiveShadow
              geometry={nodes.Bushes_2_2.geometry}
              material={materials['World ap']}
              position={[-0.952, 5.2705, 49.29652]}
              rotation={[-1.38248, -1.39866, -0.0417]}
            />
            <mesh
              name="Tree_1"
              castShadow
              receiveShadow
              geometry={nodes.Tree_1.geometry}
              material={materials['World ap']}
              position={[-20.42454, -28.77582, -82.21016]}
              rotation={[-2.97122, -0.12335, -1.78241]}
            />
            <mesh
              name="Tree_2"
              castShadow
              receiveShadow
              geometry={nodes.Tree_2.geometry}
              material={materials['World ap']}
              position={[-26.52129, -46.03793, 12.04327]}
              rotation={[-1.38248, -1.39866, -0.0417]}
            />
            <mesh
              name="Tree_3"
              castShadow
              receiveShadow
              geometry={nodes.Tree_3.geometry}
              material={materials['World ap']}
              position={[-39.24258, -27.90772, 158.02482]}
              rotation={[-0.17135, -0.16246, 1.31004]}
            />
          </group>
          <group
            name="Bushes_3_3"
            position={[180.93076, -14.54642, -70.98415]}
            rotation={[Math.PI, 0, Math.PI]}>
            <mesh
              name="Bed_4"
              castShadow
              receiveShadow
              geometry={nodes.Bed_4.geometry}
              material={materials['World ap']}
              position={[2.856, -15.8115, -38.21188]}
              rotation={[-Math.PI, 0, Math.PI]}
            />
            <mesh
              name="Bushes_15_2"
              castShadow
              receiveShadow
              geometry={nodes.Bushes_15_2.geometry}
              material={materials['World ap']}
              position={[-0.952, 5.2705, 177.88306]}
              rotation={[-1.38248, -1.39866, -0.0417]}
            />
            <mesh
              name="Bushes_2_3"
              castShadow
              receiveShadow
              geometry={nodes.Bushes_2_3.geometry}
              material={materials['World ap']}
              position={[-0.952, 5.2705, -52.61977]}
              rotation={[-1.38248, -1.39866, -0.0417]}
            />
            <mesh
              name="Bushes_4"
              castShadow
              receiveShadow
              geometry={nodes.Bushes_4.geometry}
              material={materials['World ap']}
              position={[-0.952, 5.2705, 49.29652]}
              rotation={[-1.38248, -1.39866, -0.0417]}
            />
            <mesh
              name="Tree_1_2"
              castShadow
              receiveShadow
              geometry={nodes.Tree_1_2.geometry}
              material={materials['World ap']}
              position={[-20.42454, -28.77582, -82.21016]}
              rotation={[-1.38248, -1.39866, -0.0417]}
            />
            <mesh
              name="Tree_2_2"
              castShadow
              receiveShadow
              geometry={nodes.Tree_2_2.geometry}
              material={materials['World ap']}
              position={[-34.94639, -27.90773, 12.04327]}
              rotation={[-1.38248, -1.39866, -0.0417]}
            />
            <mesh
              name="Tree_3_2"
              castShadow
              receiveShadow
              geometry={nodes.Tree_3_2.geometry}
              material={materials['World ap']}
              position={[-29.61038, -27.90772, 158.02482]}
              rotation={[-0.17135, -0.16246, 1.31004]}
            />
          </group>
          <mesh
            name="Shop"
            castShadow
            receiveShadow
            geometry={nodes.Shop.geometry}
            material={materials['World ap']}
            position={[-65.33612, -36.6329, -123.33483]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            name="Trash"
            castShadow
            receiveShadow
            geometry={nodes.Trash.geometry}
            material={materials['World ap']}
            position={[46.2633, -28.06842, 47.97817]}
            rotation={[Math.PI, 0, 0]}
          />
          <mesh
            name="Trash_2"
            castShadow
            receiveShadow
            geometry={nodes.Trash_2.geometry}
            material={materials['World ap']}
            position={[-82.15612, -28.06844, 47.97818]}
            rotation={[Math.PI, 0, 0]}
          />
        </group>
        <mesh
          name="ROAD"
          castShadow
          receiveShadow
          geometry={nodes.ROAD.geometry}
          material={materials['World ap']}
          position={[-122.39903, -16.87455, 78.99819]}
          rotation={[Math.PI / 2, 0, -Math.PI]}>
          <mesh
            name="traffic_light_2_2"
            castShadow
            receiveShadow
            geometry={nodes.traffic_light_2_2.geometry}
            material={materials['World ap']}
            position={[-878.58538, -144.63274, -92.93758]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          />
          <mesh
            name="traffic_light_1_2"
            castShadow
            receiveShadow
            geometry={nodes.traffic_light_1_2.geometry}
            material={materials['World ap']}
            position={[-241.85246, -144.63285, -92.93756]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          />
          <mesh
            name="traffic_light_2_3"
            castShadow
            receiveShadow
            geometry={nodes.traffic_light_2_3.geometry}
            material={materials['World ap']}
            position={[-878.58535, 175.52866, -92.93758]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          />
          <mesh
            name="ROAD_Lines_12"
            castShadow
            receiveShadow
            geometry={nodes.ROAD_Lines_12.geometry}
            material={materials['World ap']}
            position={[-106.27663, -127.72003, -0.40418]}
          />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/models/CityPack.gltf')
